//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteWebService.SyncConsultaColaborador {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="SyncConsultaColaborador.rubi_Synccom_senior_g5_rh_fp_consultarColaborador")]
    public interface rubi_Synccom_senior_g5_rh_fp_consultarColaborador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_Synccom_senior_g5_rh_fp_consultarColaborador/C" +
            "onsultarColaboradorRequest", ReplyAction="http://services.senior.com.br/rubi_Synccom_senior_g5_rh_fp_consultarColaborador/C" +
            "onsultarColaboradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        TesteWebService.SyncConsultaColaborador.consultarColaboradorConsultarColaboradorOut ConsultarColaborador(string user, string password, int encryption, TesteWebService.SyncConsultaColaborador.consultarColaboradorConsultarColaboradorIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_Synccom_senior_g5_rh_fp_consultarColaborador/C" +
            "onsultarColaboradorRequest", ReplyAction="http://services.senior.com.br/rubi_Synccom_senior_g5_rh_fp_consultarColaborador/C" +
            "onsultarColaboradorResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<TesteWebService.SyncConsultaColaborador.consultarColaboradorConsultarColaboradorOut> ConsultarColaboradorAsync(string user, string password, int encryption, TesteWebService.SyncConsultaColaborador.consultarColaboradorConsultarColaboradorIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class consultarColaboradorConsultarColaboradorIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private System.Nullable<int> numCadField;
        
        private bool numCadFieldSpecified;
        
        private System.Nullable<int> numEmpField;
        
        private bool numEmpFieldSpecified;
        
        private System.Nullable<int> tipColField;
        
        private bool tipColFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> numCad {
            get {
                return this.numCadField;
            }
            set {
                this.numCadField = value;
                this.RaisePropertyChanged("numCad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCadSpecified {
            get {
                return this.numCadFieldSpecified;
            }
            set {
                this.numCadFieldSpecified = value;
                this.RaisePropertyChanged("numCadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> numEmp {
            get {
                return this.numEmpField;
            }
            set {
                this.numEmpField = value;
                this.RaisePropertyChanged("numEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numEmpSpecified {
            get {
                return this.numEmpFieldSpecified;
            }
            set {
                this.numEmpFieldSpecified = value;
                this.RaisePropertyChanged("numEmpSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> tipCol {
            get {
                return this.tipColField;
            }
            set {
                this.tipColField = value;
                this.RaisePropertyChanged("tipCol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipColSpecified {
            get {
                return this.tipColFieldSpecified;
            }
            set {
                this.tipColFieldSpecified = value;
                this.RaisePropertyChanged("tipColSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class consultarColaboradorConsultarColaboradorOutTMCSColaboradores : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string catCnhField;
        
        private string codCarField;
        
        private string codCb2Field;
        
        private string codCcuField;
        
        private System.Nullable<int> codFilField;
        
        private bool codFilFieldSpecified;
        
        private System.Nullable<int> codForField;
        
        private bool codForFieldSpecified;
        
        private string codLocField;
        
        private string datAdmField;
        
        private string datAfaField;
        
        private string datNasField;
        
        private System.Nullable<int> dddTelField;
        
        private bool dddTelFieldSpecified;
        
        private System.Nullable<int> ddiTelField;
        
        private bool ddiTelFieldSpecified;
        
        private string demPspField;
        
        private string desSitField;
        
        private string dexCidField;
        
        private string dscTipColField;
        
        private string dvaPspField;
        
        private string emaComField;
        
        private string emiCidField;
        
        private string emiPspField;
        
        private System.Nullable<int> estCarField;
        
        private bool estCarFieldSpecified;
        
        private string estCidField;
        
        private string estCnhField;
        
        private string horAfaField;
        
        private string nomCcuField;
        
        private string nomEmpField;
        
        private string nomFunField;
        
        private string nomLocField;
        
        private string nomMaeField;
        
        private string nomPaiField;
        
        private System.Nullable<int> numCadField;
        
        private bool numCadFieldSpecified;
        
        private string numCgcField;
        
        private string numCidField;
        
        private string numCnhField;
        
        private string numCpfField;
        
        private System.Nullable<int> numEmpField;
        
        private bool numEmpFieldSpecified;
        
        private string numPspField;
        
        private string numTelField;
        
        private string orgCnhField;
        
        private string razSocField;
        
        private System.Nullable<int> sitAfaField;
        
        private bool sitAfaFieldSpecified;
        
        private System.Nullable<int> tabOrgField;
        
        private bool tabOrgFieldSpecified;
        
        private System.Nullable<int> tipColField;
        
        private bool tipColFieldSpecified;
        
        private System.Nullable<int> tipInsField;
        
        private bool tipInsFieldSpecified;
        
        private string tipSexField;
        
        private string titCarField;
        
        private string titRedField;
        
        private string venCnhField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string catCnh {
            get {
                return this.catCnhField;
            }
            set {
                this.catCnhField = value;
                this.RaisePropertyChanged("catCnh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codCar {
            get {
                return this.codCarField;
            }
            set {
                this.codCarField = value;
                this.RaisePropertyChanged("codCar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codCb2 {
            get {
                return this.codCb2Field;
            }
            set {
                this.codCb2Field = value;
                this.RaisePropertyChanged("codCb2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string codCcu {
            get {
                return this.codCcuField;
            }
            set {
                this.codCcuField = value;
                this.RaisePropertyChanged("codCcu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilSpecified {
            get {
                return this.codFilFieldSpecified;
            }
            set {
                this.codFilFieldSpecified = value;
                this.RaisePropertyChanged("codFilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> codFor {
            get {
                return this.codForField;
            }
            set {
                this.codForField = value;
                this.RaisePropertyChanged("codFor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codForSpecified {
            get {
                return this.codForFieldSpecified;
            }
            set {
                this.codForFieldSpecified = value;
                this.RaisePropertyChanged("codForSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string codLoc {
            get {
                return this.codLocField;
            }
            set {
                this.codLocField = value;
                this.RaisePropertyChanged("codLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string datAdm {
            get {
                return this.datAdmField;
            }
            set {
                this.datAdmField = value;
                this.RaisePropertyChanged("datAdm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string datAfa {
            get {
                return this.datAfaField;
            }
            set {
                this.datAfaField = value;
                this.RaisePropertyChanged("datAfa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string datNas {
            get {
                return this.datNasField;
            }
            set {
                this.datNasField = value;
                this.RaisePropertyChanged("datNas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<int> dddTel {
            get {
                return this.dddTelField;
            }
            set {
                this.dddTelField = value;
                this.RaisePropertyChanged("dddTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dddTelSpecified {
            get {
                return this.dddTelFieldSpecified;
            }
            set {
                this.dddTelFieldSpecified = value;
                this.RaisePropertyChanged("dddTelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<int> ddiTel {
            get {
                return this.ddiTelField;
            }
            set {
                this.ddiTelField = value;
                this.RaisePropertyChanged("ddiTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ddiTelSpecified {
            get {
                return this.ddiTelFieldSpecified;
            }
            set {
                this.ddiTelFieldSpecified = value;
                this.RaisePropertyChanged("ddiTelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string demPsp {
            get {
                return this.demPspField;
            }
            set {
                this.demPspField = value;
                this.RaisePropertyChanged("demPsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string desSit {
            get {
                return this.desSitField;
            }
            set {
                this.desSitField = value;
                this.RaisePropertyChanged("desSit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string dexCid {
            get {
                return this.dexCidField;
            }
            set {
                this.dexCidField = value;
                this.RaisePropertyChanged("dexCid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string dscTipCol {
            get {
                return this.dscTipColField;
            }
            set {
                this.dscTipColField = value;
                this.RaisePropertyChanged("dscTipCol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string dvaPsp {
            get {
                return this.dvaPspField;
            }
            set {
                this.dvaPspField = value;
                this.RaisePropertyChanged("dvaPsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string emaCom {
            get {
                return this.emaComField;
            }
            set {
                this.emaComField = value;
                this.RaisePropertyChanged("emaCom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public string emiCid {
            get {
                return this.emiCidField;
            }
            set {
                this.emiCidField = value;
                this.RaisePropertyChanged("emiCid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string emiPsp {
            get {
                return this.emiPspField;
            }
            set {
                this.emiPspField = value;
                this.RaisePropertyChanged("emiPsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public System.Nullable<int> estCar {
            get {
                return this.estCarField;
            }
            set {
                this.estCarField = value;
                this.RaisePropertyChanged("estCar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estCarSpecified {
            get {
                return this.estCarFieldSpecified;
            }
            set {
                this.estCarFieldSpecified = value;
                this.RaisePropertyChanged("estCarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string estCid {
            get {
                return this.estCidField;
            }
            set {
                this.estCidField = value;
                this.RaisePropertyChanged("estCid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public string estCnh {
            get {
                return this.estCnhField;
            }
            set {
                this.estCnhField = value;
                this.RaisePropertyChanged("estCnh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public string horAfa {
            get {
                return this.horAfaField;
            }
            set {
                this.horAfaField = value;
                this.RaisePropertyChanged("horAfa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public string nomCcu {
            get {
                return this.nomCcuField;
            }
            set {
                this.nomCcuField = value;
                this.RaisePropertyChanged("nomCcu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=25)]
        public string nomEmp {
            get {
                return this.nomEmpField;
            }
            set {
                this.nomEmpField = value;
                this.RaisePropertyChanged("nomEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=26)]
        public string nomFun {
            get {
                return this.nomFunField;
            }
            set {
                this.nomFunField = value;
                this.RaisePropertyChanged("nomFun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=27)]
        public string nomLoc {
            get {
                return this.nomLocField;
            }
            set {
                this.nomLocField = value;
                this.RaisePropertyChanged("nomLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=28)]
        public string nomMae {
            get {
                return this.nomMaeField;
            }
            set {
                this.nomMaeField = value;
                this.RaisePropertyChanged("nomMae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public string nomPai {
            get {
                return this.nomPaiField;
            }
            set {
                this.nomPaiField = value;
                this.RaisePropertyChanged("nomPai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=30)]
        public System.Nullable<int> numCad {
            get {
                return this.numCadField;
            }
            set {
                this.numCadField = value;
                this.RaisePropertyChanged("numCad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCadSpecified {
            get {
                return this.numCadFieldSpecified;
            }
            set {
                this.numCadFieldSpecified = value;
                this.RaisePropertyChanged("numCadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=31)]
        public string numCgc {
            get {
                return this.numCgcField;
            }
            set {
                this.numCgcField = value;
                this.RaisePropertyChanged("numCgc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=32)]
        public string numCid {
            get {
                return this.numCidField;
            }
            set {
                this.numCidField = value;
                this.RaisePropertyChanged("numCid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=33)]
        public string numCnh {
            get {
                return this.numCnhField;
            }
            set {
                this.numCnhField = value;
                this.RaisePropertyChanged("numCnh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=34)]
        public string numCpf {
            get {
                return this.numCpfField;
            }
            set {
                this.numCpfField = value;
                this.RaisePropertyChanged("numCpf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=35)]
        public System.Nullable<int> numEmp {
            get {
                return this.numEmpField;
            }
            set {
                this.numEmpField = value;
                this.RaisePropertyChanged("numEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numEmpSpecified {
            get {
                return this.numEmpFieldSpecified;
            }
            set {
                this.numEmpFieldSpecified = value;
                this.RaisePropertyChanged("numEmpSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=36)]
        public string numPsp {
            get {
                return this.numPspField;
            }
            set {
                this.numPspField = value;
                this.RaisePropertyChanged("numPsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=37)]
        public string numTel {
            get {
                return this.numTelField;
            }
            set {
                this.numTelField = value;
                this.RaisePropertyChanged("numTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=38)]
        public string orgCnh {
            get {
                return this.orgCnhField;
            }
            set {
                this.orgCnhField = value;
                this.RaisePropertyChanged("orgCnh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=39)]
        public string razSoc {
            get {
                return this.razSocField;
            }
            set {
                this.razSocField = value;
                this.RaisePropertyChanged("razSoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=40)]
        public System.Nullable<int> sitAfa {
            get {
                return this.sitAfaField;
            }
            set {
                this.sitAfaField = value;
                this.RaisePropertyChanged("sitAfa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitAfaSpecified {
            get {
                return this.sitAfaFieldSpecified;
            }
            set {
                this.sitAfaFieldSpecified = value;
                this.RaisePropertyChanged("sitAfaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=41)]
        public System.Nullable<int> tabOrg {
            get {
                return this.tabOrgField;
            }
            set {
                this.tabOrgField = value;
                this.RaisePropertyChanged("tabOrg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tabOrgSpecified {
            get {
                return this.tabOrgFieldSpecified;
            }
            set {
                this.tabOrgFieldSpecified = value;
                this.RaisePropertyChanged("tabOrgSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=42)]
        public System.Nullable<int> tipCol {
            get {
                return this.tipColField;
            }
            set {
                this.tipColField = value;
                this.RaisePropertyChanged("tipCol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipColSpecified {
            get {
                return this.tipColFieldSpecified;
            }
            set {
                this.tipColFieldSpecified = value;
                this.RaisePropertyChanged("tipColSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=43)]
        public System.Nullable<int> tipIns {
            get {
                return this.tipInsField;
            }
            set {
                this.tipInsField = value;
                this.RaisePropertyChanged("tipIns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipInsSpecified {
            get {
                return this.tipInsFieldSpecified;
            }
            set {
                this.tipInsFieldSpecified = value;
                this.RaisePropertyChanged("tipInsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=44)]
        public string tipSex {
            get {
                return this.tipSexField;
            }
            set {
                this.tipSexField = value;
                this.RaisePropertyChanged("tipSex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=45)]
        public string titCar {
            get {
                return this.titCarField;
            }
            set {
                this.titCarField = value;
                this.RaisePropertyChanged("titCar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=46)]
        public string titRed {
            get {
                return this.titRedField;
            }
            set {
                this.titRedField = value;
                this.RaisePropertyChanged("titRed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=47)]
        public string venCnh {
            get {
                return this.venCnhField;
            }
            set {
                this.venCnhField = value;
                this.RaisePropertyChanged("venCnh");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class consultarColaboradorConsultarColaboradorOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private consultarColaboradorConsultarColaboradorOutTMCSColaboradores[] tMCSColaboradoresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TMCSColaboradores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public consultarColaboradorConsultarColaboradorOutTMCSColaboradores[] TMCSColaboradores {
            get {
                return this.tMCSColaboradoresField;
            }
            set {
                this.tMCSColaboradoresField = value;
                this.RaisePropertyChanged("TMCSColaboradores");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface rubi_Synccom_senior_g5_rh_fp_consultarColaboradorChannel : TesteWebService.SyncConsultaColaborador.rubi_Synccom_senior_g5_rh_fp_consultarColaborador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class rubi_Synccom_senior_g5_rh_fp_consultarColaboradorClient : System.ServiceModel.ClientBase<TesteWebService.SyncConsultaColaborador.rubi_Synccom_senior_g5_rh_fp_consultarColaborador>, TesteWebService.SyncConsultaColaborador.rubi_Synccom_senior_g5_rh_fp_consultarColaborador {
        
        public rubi_Synccom_senior_g5_rh_fp_consultarColaboradorClient() {
        }
        
        public rubi_Synccom_senior_g5_rh_fp_consultarColaboradorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public rubi_Synccom_senior_g5_rh_fp_consultarColaboradorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rubi_Synccom_senior_g5_rh_fp_consultarColaboradorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rubi_Synccom_senior_g5_rh_fp_consultarColaboradorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TesteWebService.SyncConsultaColaborador.consultarColaboradorConsultarColaboradorOut ConsultarColaborador(string user, string password, int encryption, TesteWebService.SyncConsultaColaborador.consultarColaboradorConsultarColaboradorIn parameters) {
            return base.Channel.ConsultarColaborador(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<TesteWebService.SyncConsultaColaborador.consultarColaboradorConsultarColaboradorOut> ConsultarColaboradorAsync(string user, string password, int encryption, TesteWebService.SyncConsultaColaborador.consultarColaboradorConsultarColaboradorIn parameters) {
            return base.Channel.ConsultarColaboradorAsync(user, password, encryption, parameters);
        }
    }
}
