//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.MCWFU {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="MCWFU.rubi_AsyncMCWFUsers")]
    public interface rubi_AsyncMCWFUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/DiscoverUsersGroupsRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/DiscoverUsersGroupsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string DiscoverUsersGroups(string user, string password, int encryption, Teste.MCWFU.mcwfUsersDiscoverUsersGroupsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/DiscoverUsersGroupsRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/DiscoverUsersGroupsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> DiscoverUsersGroupsAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersDiscoverUsersGroupsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/PersonExistsRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/PersonExistsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string PersonExists(string user, string password, int encryption, Teste.MCWFU.mcwfUsersPersonExistsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/PersonExistsRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/PersonExistsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> PersonExistsAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersPersonExistsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/GetUserGroupsRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/GetUserGroupsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string GetUserGroups(string user, string password, int encryption, Teste.MCWFU.mcwfUsersGetUserGroupsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/GetUserGroupsRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/GetUserGroupsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> GetUserGroupsAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersGetUserGroupsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/GetPersonKindRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/GetPersonKindResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string GetPersonKind(string user, string password, int encryption, Teste.MCWFU.mcwfUsersGetPersonKindIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/GetPersonKindRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/GetPersonKindResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> GetPersonKindAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersGetPersonKindIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/UserReplicationRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/UserReplicationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string UserReplication(string user, string password, int encryption, Teste.MCWFU.mcwfUsersUserReplicationIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/UserReplicationRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/UserReplicationResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> UserReplicationAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersUserReplicationIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/ChangePasswordRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/ChangePasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string ChangePassword(string user, string password, int encryption, Teste.MCWFU.mcwfUsersChangePasswordIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/ChangePasswordRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/ChangePasswordResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> ChangePasswordAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersChangePasswordIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/AuthenticateJAASRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/AuthenticateJAASResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string AuthenticateJAAS(string user, string password, int encryption, Teste.MCWFU.mcwfUsersAuthenticateJAASIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_AsyncMCWFUsers/AuthenticateJAASRequest", ReplyAction="http://services.senior.com.br/rubi_AsyncMCWFUsers/AuthenticateJAASResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<string> AuthenticateJAASAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersAuthenticateJAASIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersDiscoverUsersGroupsIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersAuthenticateJAASIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private System.Nullable<int> pmEncryptedField;
        
        private bool pmEncryptedFieldSpecified;
        
        private string pmUserNameField;
        
        private string pmUserPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> pmEncrypted {
            get {
                return this.pmEncryptedField;
            }
            set {
                this.pmEncryptedField = value;
                this.RaisePropertyChanged("pmEncrypted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pmEncryptedSpecified {
            get {
                return this.pmEncryptedFieldSpecified;
            }
            set {
                this.pmEncryptedFieldSpecified = value;
                this.RaisePropertyChanged("pmEncryptedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string pmUserName {
            get {
                return this.pmUserNameField;
            }
            set {
                this.pmUserNameField = value;
                this.RaisePropertyChanged("pmUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string pmUserPassword {
            get {
                return this.pmUserPasswordField;
            }
            set {
                this.pmUserPasswordField = value;
                this.RaisePropertyChanged("pmUserPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersChangePasswordIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmNewPasswordField;
        
        private string pmNewPasswordConfirmationField;
        
        private string pmPasswordField;
        
        private string pmUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmNewPassword {
            get {
                return this.pmNewPasswordField;
            }
            set {
                this.pmNewPasswordField = value;
                this.RaisePropertyChanged("pmNewPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string pmNewPasswordConfirmation {
            get {
                return this.pmNewPasswordConfirmationField;
            }
            set {
                this.pmNewPasswordConfirmationField = value;
                this.RaisePropertyChanged("pmNewPasswordConfirmation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string pmPassword {
            get {
                return this.pmPasswordField;
            }
            set {
                this.pmPasswordField = value;
                this.RaisePropertyChanged("pmPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string pmUser {
            get {
                return this.pmUserField;
            }
            set {
                this.pmUserField = value;
                this.RaisePropertyChanged("pmUser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersUserReplicationIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmUserReplicationXMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmUserReplicationXML {
            get {
                return this.pmUserReplicationXMLField;
            }
            set {
                this.pmUserReplicationXMLField = value;
                this.RaisePropertyChanged("pmUserReplicationXML");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersGetPersonKindIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmPersonNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmPersonName {
            get {
                return this.pmPersonNameField;
            }
            set {
                this.pmPersonNameField = value;
                this.RaisePropertyChanged("pmPersonName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersGetUserGroupsIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmGetUserGroupsUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmGetUserGroupsUserName {
            get {
                return this.pmGetUserGroupsUserNameField;
            }
            set {
                this.pmGetUserGroupsUserNameField = value;
                this.RaisePropertyChanged("pmGetUserGroupsUserName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersPersonExistsIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmPersonKindField;
        
        private string pmPersonNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmPersonKind {
            get {
                return this.pmPersonKindField;
            }
            set {
                this.pmPersonKindField = value;
                this.RaisePropertyChanged("pmPersonKind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string pmPersonName {
            get {
                return this.pmPersonNameField;
            }
            set {
                this.pmPersonNameField = value;
                this.RaisePropertyChanged("pmPersonName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface rubi_AsyncMCWFUsersChannel : Teste.MCWFU.rubi_AsyncMCWFUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class rubi_AsyncMCWFUsersClient : System.ServiceModel.ClientBase<Teste.MCWFU.rubi_AsyncMCWFUsers>, Teste.MCWFU.rubi_AsyncMCWFUsers {
        
        public rubi_AsyncMCWFUsersClient() {
        }
        
        public rubi_AsyncMCWFUsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public rubi_AsyncMCWFUsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rubi_AsyncMCWFUsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rubi_AsyncMCWFUsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DiscoverUsersGroups(string user, string password, int encryption, Teste.MCWFU.mcwfUsersDiscoverUsersGroupsIn parameters) {
            return base.Channel.DiscoverUsersGroups(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<string> DiscoverUsersGroupsAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersDiscoverUsersGroupsIn parameters) {
            return base.Channel.DiscoverUsersGroupsAsync(user, password, encryption, parameters);
        }
        
        public string PersonExists(string user, string password, int encryption, Teste.MCWFU.mcwfUsersPersonExistsIn parameters) {
            return base.Channel.PersonExists(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<string> PersonExistsAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersPersonExistsIn parameters) {
            return base.Channel.PersonExistsAsync(user, password, encryption, parameters);
        }
        
        public string GetUserGroups(string user, string password, int encryption, Teste.MCWFU.mcwfUsersGetUserGroupsIn parameters) {
            return base.Channel.GetUserGroups(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<string> GetUserGroupsAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersGetUserGroupsIn parameters) {
            return base.Channel.GetUserGroupsAsync(user, password, encryption, parameters);
        }
        
        public string GetPersonKind(string user, string password, int encryption, Teste.MCWFU.mcwfUsersGetPersonKindIn parameters) {
            return base.Channel.GetPersonKind(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<string> GetPersonKindAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersGetPersonKindIn parameters) {
            return base.Channel.GetPersonKindAsync(user, password, encryption, parameters);
        }
        
        public string UserReplication(string user, string password, int encryption, Teste.MCWFU.mcwfUsersUserReplicationIn parameters) {
            return base.Channel.UserReplication(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<string> UserReplicationAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersUserReplicationIn parameters) {
            return base.Channel.UserReplicationAsync(user, password, encryption, parameters);
        }
        
        public string ChangePassword(string user, string password, int encryption, Teste.MCWFU.mcwfUsersChangePasswordIn parameters) {
            return base.Channel.ChangePassword(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<string> ChangePasswordAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersChangePasswordIn parameters) {
            return base.Channel.ChangePasswordAsync(user, password, encryption, parameters);
        }
        
        public string AuthenticateJAAS(string user, string password, int encryption, Teste.MCWFU.mcwfUsersAuthenticateJAASIn parameters) {
            return base.Channel.AuthenticateJAAS(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateJAASAsync(string user, string password, int encryption, Teste.MCWFU.mcwfUsersAuthenticateJAASIn parameters) {
            return base.Channel.AuthenticateJAASAsync(user, password, encryption, parameters);
        }
    }
}
